[package]
name = "aoc2020"
version = "0.1.0"
authors = ["azuline <azuline@riseup.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "aoc2020"
path = "rust/main.rs"

[dependencies]
itertools = "0.9"
